//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympiad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificates
    {
        public int CertificateId { get; set; }
        public int OlympiadId { get; set; }
        public string FilePath { get; set; }
        public string Description { get; set; }
    
        public virtual Olympiads Olympiads { get; set; }
    }
}
