//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympiad.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlympiadTrackingEntities : DbContext
    {
        public OlympiadTrackingEntities()
            : base("name=OlympiadTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certificates> Certificates { get; set; }
        public virtual DbSet<Olympiads> Olympiads { get; set; }
        public virtual DbSet<Protocols> Protocols { get; set; }
        public virtual DbSet<Registrations> Registrations { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
