//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympiad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registrations()
        {
            this.Results = new HashSet<Results>();
        }
    
        public int RegistrationId { get; set; }
        public int StudentUserId { get; set; }
        public int OlympiadId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual Olympiads Olympiads { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }
    }
}
